spring.application.name=springBootApp

management.info.env.enabled=true

info.app.name=springBootApp
info.app.description=This is a basic spring boot application
info.app.version=1.0

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=

server.port=8081
server.servlet.context-path=/springBootApp

coach.name=John
player.name=Doe